services:
  db:
    image: mariadb:10.11
    container_name: detailing-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_aici
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password_aici
    volumes:
      - ./data/db:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d      

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: detailing-wp
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password_aici
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./data/wordpress:/var/www/html

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: detailing-proxy
    restart: always
    ports:
      - '8080:80'   # HTTP accesibil la http://detailing.test:8080
      - '8443:443' # HTTPS accesibil la https://detailing.test:8443
      - '8181:81'   # Admin UI la http://localhost:8181
    volumes:
      - ./data/nginx-proxy/config:/data
      - ./data/nginx-proxy/letsencrypt:/etc/letsencrypt

networks:
  default:
    name: detailing-network